services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

