apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-microservice
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-microservice
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/microservices-457414/image-registry/auth-microservice
        name: auth-microservice
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats-server"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
        resources: {}
status: {}
