apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-microservice
  name: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-microservice
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/microservices-457414/image-registry/orders-microservice
        name: orders-microservice
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats-server"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: orders-secrets
                key: DATABASE_URL
        resources: {}
status: {}
